import type { NextPage } from 'next'
import Head from 'next/head'
import { PostCard, Categories, PostWidget, Header} from '../components'
import {getPosts} from '../services/index'

const Home: NextPage = ({posts}:any) => {
  console.log(posts);
  return (
    <div className="container mx-auto px-10 mb-8 ">
      <Head>
        <title>Post It. It&apos;s Simple</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='grid grid-cols-1 lg:grid-cols-12 gap-12'>
        <div className='lg:col-span-8 col-span-1'>
          {posts.map((post:any) => (
           <PostCard post={post.node} key={post.node.title} />
          ))}
        </div>
        <div className='lg:col-span-4 col-span-1'>
            <div className='lg:sticky relative top-8'>
              <PostWidget />
              <Categories />
            </div>
        </div>
      </div>
    </div>
  )
}

export async function getStaticProps() {
  const posts = (await getPosts()) || [];
  return {
    props: {posts}
  }
};

export default Home
